In [1]:
import numpy as np

# Create a 3-dimensional array (2x3x4)
array_3d = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],

                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

print("3D Array:")
print(array_3d)

# Indexing examples
# 1. Access element at 1st block, 2nd row, 3rd column
element = array_3d[0, 1, 2]
print("\nElement at [0, 1, 2]:", element)

# 2. Access the 2nd row of the 1st block
row = array_3d[0, 1, :]
print("\n2nd row of 1st block:", row)

# 3. Access all elements in the 3rd column across both blocks
column = array_3d[:, :, 2]
print("\n3rd column across both blocks:")
print(column)

# 4. Access the entire 2nd block
block = array_3d[1, :, :]
print("\n2nd block:")
print(block)


3D Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Element at [0, 1, 2]: 7

2nd row of 1st block: [5 6 7 8]

3rd column across both blocks:
[[ 3  7 11]
 [15 19 23]]

2nd block:
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [2]:
d = {1: 2, 2: 3, 3: 4, 4: 5}

# Create an array of squares of keys
squares_of_keys = [key**2 for key in d.keys()]
print("Squares of keys:", squares_of_keys)


Squares of keys: [1, 4, 9, 16]


In [3]:
import numpy as np

# Create a 2-dimensional array (2x2)
array_2d = np.array([[3, 4],
                     [5, 6]])

# Create a 2x2 identity matrix
identity_matrix = np.eye(2)

# Multiply the array by the identity matrix
result = np.dot(array_2d, identity_matrix)

print("Original Array:")
print(array_2d)

print("\nIdentity Matrix:")
print(identity_matrix)

print("\nResult of Multiplication:")
print(result)


Original Array:
[[3 4]
 [5 6]]

Identity Matrix:
[[1. 0.]
 [0. 1.]]

Result of Multiplication:
[[3. 4.]
 [5. 6.]]
